# Generated by Django 5.2.6 on 2025-11-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Sector',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
