# Generated by Django 5.2.6 on 2025-11-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipms_app', '0002_user_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Sector',
            new_name='sector',
        ),
    ]
