# Generated by Django 5.2.6 on 2025-11-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipms_app', '0003_rename_sector_user_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SCHOOL', 'School'), ('UMURENGE', 'Umurenge'), ('DISTRICT', 'District'), ('MINEDUC', 'Mineduc'), ('ADMIN', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
