# Generated by Django 5.2.6 on 2025-11-20 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipms_app', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='prediction_reports/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction Report',
                'verbose_name_plural': 'Prediction Reports',
                'db_table': 'prediction_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
