# Generated by Django 5.2.6 on 2025-11-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipms_app', '0005_predictionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionreport',
            name='is_sent_to_mineduc',
            field=models.BooleanField(default=False),
        ),
    ]
