# Generated by Django 5.2.6 on 2025-11-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipms_app', '0006_predictionreport_is_sent_to_mineduc'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionreport',
            name='denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
