# Generated by Django 5.2.6 on 2025-12-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipms_app', '0007_predictionreport_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('UMURENGE', 'Umurenge'), ('DISTRICT', 'District'), ('MINEDUC', 'Mineduc'), ('ADMIN', 'Admin')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
